test_token=''
appid = ''
secret = ''
reserve_url = 'localhost'
reserve_port = 80
template_id_remind_f20 = ''
template_id_remind_fib = ''
redis_host = 'localhost'
redis_password = ''
redis_expire_time = 300
mysql_host = 'localhost'
mysql_password = ''
